# syntax=docker/dockerfile:1.3-labs

FROM alpine:3.22

# run wo/ heredoc
RUN echo 'hello 1 from inline'; \
    echo 'hello 2 from inline'

# run w/ heredoc
RUN <<EOT
apk add --no-cache curl jq skopeo python3

cat > result.txt << EOFF
Hello 1 from result.txt using heredoc
Hello 2 from result.txt using heredoc
EOFF

EOT

RUN cat result.txt

RUN <<EOT
echo 'Hello 1 from heredoc'
echo 'Hello 2 from heredoc'
EOT

RUN <<"EOF"
python3 <<EOT
a = 2
if a == 2:
    print("a is 2")
else:
    print("a is not 2")
EOT
EOF

RUN cat <<file1.txt > /tmp/file1.txt && cat <<file2.txt > /tmp/file2.txt
Hello from file1
file1.txt
Hello from file2
file2.txt

ENTRYPOINT ["/bin/sh"]